"""Initial migration after reset

Revision ID: 18803897ae7d
Revises: 
Create Date: 2024-09-10 20:23:18.467716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18803897ae7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_game',
    sa.Column('player_id', sa.String(length=36), nullable=True),
    sa.Column('game_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_game')
    # ### end Alembic commands ###
